config/routes.rb
Rails.application.routes.draw do
	root to: 'urls#new'
	resources :urls, only: [:create, :show, :new]
	get "/:short_url", to: "urls#redirect_to_original_url"

	get 'auth/:provider/callback', to: 'sessions#create'
	get 'auth/failure', to: redirect('/')
	get 'sessions/signout', to: 'sessions#destroy', as: 'signout'

	resources :sessions, only: [:create, :destroy]
end

app/models/url.rb
class Url < ActiveRecord::Base
	validates :original_url, presence: true
	before_create :create_short_url

	def create_short_url
		chars_arr = [('A'..'Z'),('a'..'z'),('0'..'9')].map(&:to_a).flatten
		self.short_url = chars_arr.sample(5).join
    self.short_url = chars_arr.sample(5).join until Url.find_by_short_url(self.short_url).nil?
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
	before_action :set_url, only: [:show, :edit, :update, :destroy]

	def show
	end

	def redirect_to_original_url
		@url = Url.find_by_short_url(params[:short_url])
		redirect_to @url.original_url
	end

	def new
		@url = Url.new
	end

	def create
		@url = Url.new(url_params)
		respond_to do |format|
			if @url.save
				format.html { redirect_to @url, notice: 'Your url has been shorten successfully.' }
				format.json { render :show, status: :created, location: @url }
			else
				format.html { render :new }
				format.json { render json: @url.errors, status: :unprocessable_entity }
			end
		end
	end

	private
		def set_url
			@url = Url.find(params[:id])
		end

		def url_params
			params.require(:url).permit(:original_url)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div>
   	<%= yield %>
  </div>
  </br>
  </br>
	<div>
    <% if current_user %>
      Signed in as <strong><%= current_user.name %></strong>!
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% else %>
      <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
    <% end %>
  </div>
</body>
</html>

app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
	<% if @url.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

			<ul>
			<% @url.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :original_url %><br>
		<%= f.text_field :original_url %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/urls/new.html.erb
<% if current_user %>
	<h1>Please enter the URL.</h1>

	<%= render 'form' %>
<%else%>
	<div>
	  <h1>Welcome!</h1>
	  <p>Authenticate via Google Account to shorten your URL.</p>
	</div>
<%end%>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Original url:</strong>
  <%= @url.original_url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= link_to("#{request.base_url}/#{@url.short_url}",{controller: 'urls', action: 'redirect_to_original_url', short_url: @url.short_url}, target: '_blank') %>
</p>

<%= link_to 'Back', new_url_path %>